### ISSUE TITLE
make archive reproducible

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/obs-service-node_modules#27]
It is probably possible to make the produced archive reproducible. Currently even if the content is the same, the archive is not:

```
> diffoscope systemsmanagement\:cockpit/cockpit/node_modules.obscpio ~/systemsmanagement\:cockpit/cockpit/node_modules.obscpio
[snip]
│ --rw-r--r--   1     1006      100     2765 2022-07-19 10:27:27.000000 yocto-queue-0.1.0.tgz
[snip]
│ +-rw-r--r--   1     1000      100     2765 2022-01-28 14:23:18.000000 yocto-queue-0.1.0.tgz
```

To solve this probably, after writing the file in:
https://github.com/openSUSE/obs-service-node_modules/blob/master/node_modules.py#L451
Set owner and group to nobody and mtime to 0.

**Comment by JanZerebecki** [comment]
Ah, chown will obviously not work.

A better way is to change the cpio writer to hard coded values:
https://github.com/openSUSE/obs-service-node_modules/blob/ffdf74f874f3c9f79d05547050adbd93c7296c3c/node_modules.py#L150

See for comparison what the scm service does:
https://github.com/openSUSE/obs-service-tar_scm/blob/034d18d00a8d91a68132ae34df6bc2d7fdfc7529/TarSCM/archive.py#L71

**Comment by AdamMajer** [comment]
I agree. There is no reason to have non-fixed permissions or userid data here.
