### ISSUE TITLE
Question: How to handle projects that require Yarn.

### ISSUE THREAD

**Issue by ChrTall** [openSUSE/obs-service-node_modules#28]
I am currently trying to package 
[https://github.com/marktext/marktext](https://github.com/marktext/marktext)

They require yarn, which is hardcoded in their scripts, so `npm install --package-lock-only --legacy-peer-deps` fails.
Is it possible to create a yarn.lock and rename it or is npm required for the service to work?

**Comment by AdamMajer** [comment]
It requires npm to run. But keep in mind the recommended way of installing things is `--ignore-scripts` so that random scripts are not running. You can then run these at some later directly.
