### ISSUE TITLE
update to support package-lock.json with lockfileVersion": 3

### ISSUE THREAD

**Issue by ahmedmoselhi** [openSUSE/obs-service-node_modules#29]
npm perior to 9 now gives package-lock.json with lockfileVersion": 3 
please update sevice to support this file format

**Comment by AdamMajer** [comment]
This is now fixed via https://github.com/openSUSE/obs-service-node_modules/commit/1e12d0858ad21dd58aaaf8231c0e5d039ae4cf4f
