### ISSUE TITLE
Downloading modules in a subdirectory

### ISSUE THREAD

**Issue by weberhofer** [openSUSE/obs-service-node_modules#38]
This package looks very good.
I a current use-case I'd required all the processing to happen in a sub-directory of the package.
 In my case, in the source's root folder a go program is to be compiled that comes along with a "webui/" directory containing a frontend to be built using yarn.

Is there a way to tell the service to process the sub-folder instead of the root folder?

**Comment by AdamMajer** [comment]
I'm assuming you are referring to the https://github.com/openSUSE/npm-localhost-proxy ?

`cd webui; local-npm-registry %{_sourcedir} install ...`

**Comment by weberhofer** [comment]
Thanks for this hint. Now I understand how to use it. Works nicely. I'll post a reference to a project as when finished for documentation.
