### ISSUE TITLE
Feature Request: Work with a yarn.lock?

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/obs-service-node_modules#42]
Dear maintainers,

I come across npm proejcts once in a while and noticed that some of them use a `yarn.lock` instead of a `package-lock.json`. While I could convert them using something like [synp](https://github.com/imsnif/synp), this breaks the workflow completely.

Would it be possible to have the service work with yarn instead of npm, if the user hands over a `yarn.lock` instead of a `package-lock.json`?

Or should this be a different service?

Kind Regards,
Johannes

**Comment by AdamMajer** [comment]
For yarn, there is also a feature in yarn that does this via "offline-mirror" -- this is essentially exactly what this service + https://github.com/openSUSE/npm-localhost-proxy do for npm.

https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/

**Comment by johanneskastl** [comment]
Thanks for the information, Adam. I'll give it a try.

But not having this in the node_modules service means I have to do this manually (aka Makefile), hence my idea to have this as a service.
